version: '3.8'

services:
  grafana-agent:
    image: grafana/agent:latest
    container_name: gymapi_grafana_agent
    volumes:
      - ./grafana-agent-config.yml:/etc/agent-config/agent.yml
    ports:
      - "12345:12345"
    command:
      - -config.file=/etc/agent-config/agent.yml
      - -metrics.wal-directory=/tmp/wal
    environment:
      - HOSTNAME=gymapi-agent
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Para acceder a tu API en localhost
    restart: unless-stopped